// TODO: Make dynamic
// Global
import '../css/global/normalize.css';
import '../css/global/button.css';
import '../css/global/form.css';
import '../css/global/helper.css';
import '../css/global/layout.css';
import '../css/global/link.css';
import '../css/global/modal.css';
import '../css/global/typography.css';
import '../css/global/variable.css';
import '../css/global/wordpress.css';
// Modules
import '../../modules/copyright/copyright.css';
import '../../modules/consultation/consultation.css';
import '../../modules/contact/contact.css';
import '../../modules/content/content.css';
import '../../modules/footer/footer.css';
import '../../modules/header/header.css';
import '../../modules/hero/hero.css';
import '../../modules/logo/logo.css';
import '../../modules/menu/menu.css';
import '../../modules/menu-footer/menu-footer.css';
import '../../modules/menu-footer-secondary/menu-footer-secondary.css';
import '../../modules/menu-mobile/menu-mobile.css';
import '../../modules/phone/phone.css';
import '../../modules/search/search.css';
import '../../modules/social/social.css';