// TODO: Make dynamic
// Global
import '../css/global/normalize.css';
import '../css/global/button.css';
import '../css/global/form.css';
import '../css/global/helper.css';
import '../css/global/layout.css';
import '../css/global/link.css';
import '../css/global/modal.css';
import '../css/global/typography.css';
import '../css/global/variable.css';
import '../css/global/wordpress.css';
// Modules
import '../../modules/copyright/copyright.css';
import '../../modules/the-content/the-content.css';
import '../../modules/footer/footer.css';
import '../../modules/header/header.css';
import '../../modules/logo/logo.css';
import '../../modules/featured-image/featured-image.css';
import '../../modules/page-title/page-title.css';
import '../../modules/post-meta/post-meta.css';
import '../../modules/menu-header/menu-header.css';
import '../../modules/menu-footer/menu-footer.css';
import '../../modules/menu-footer-secondary/menu-footer-secondary.css';
import '../../modules/phone/phone.css';
import '../../modules/search/search.css';
import '../../modules/menu-social/menu-social.css';