stages:
  - build
  - test
  - stage
  - develop
variables:
  # Your theme folder name
  THEME_NAME: starter-theme-v2
  # Slug of your Pantheon site
  PANTHEON_NAME: hoverboard-custom-upstream
lint:
  before_script:
    - cd ./wp-content/themes/$THEME_NAME
    - npm ci
  image: node:14
  stage: test
  script: npm run lint
phpcs:
  before_script:
    - cd ./wp-content/themes/$THEME_NAME
  image: composer:2
  stage: test
  script:
    - ./bin/phpcs.sh
