stages:
  - build
  - test
  - stage
  - develop
variables:
  # Your theme folder name
  THEME_NAME: starter-theme
  # Slug of your Pantheon site
  PANTHEON_NAME: hoverboard-custom-upstream
php_syntax:
  before_script:
    - apt-get update && apt-get -y install git
    - php -v
  image: php:7
  stage: test
  script:
    - php -v
    - git diff --diff-filter=ACMR --name-only origin/master -- '*.php' | xargs -L1 php -d short_open_tag=Off -l
lint:
  before_script:
    - cd ./wp-content/themes/$THEME_NAME
    - npm ci
  image: node:10
  stage: test
  script: npm run lint