stages:
  - build
  - test
  - stage
  - develop
variables:
  # Your theme folder name
  THEME_NAME: starter-theme-v2
  # Slug of your Pantheon site
  PANTHEON_NAME: hoverboard-custom-upstream
php_syntax:
  before_script:
    - apt-get update && apt-get -y install git
    - git config --global user.email "hi@hoverboardstudios.com" && git config --global user.name "Hoverboard"
    - php -v
  image: php:7
  stage: test
  script:
    - php -v
    - git pull origin master
    - git diff --diff-filter=ACMR --name-only origin/master -- '*.php' | xargs -L1 php -d short_open_tag=Off -l
lint:
  before_script:
    - cd ./wp-content/themes/$THEME_NAME
    - npm install
  image: node:10
  stage: test
  script: npm run lint
phpcs:
  before_script:
    - cd ./wp-content/themes/$THEME_NAME
  image: composer:1.9.3
  stage: test
  script:
    - ./bash_scripts/phpcs.sh
