stages:
  - test
variables:
  # Your theme folder name
  THEME_NAME: starter-theme-v2
lint:
  before_script:
    - cd ./wp-content/themes/$THEME_NAME
    - npm ci
  image: node:14
  stage: test
  script: npm run lint
  only:
    - merge_requests
phpcs:
  before_script:
    - cd ./wp-content/themes/$THEME_NAME
  image: composer:2
  stage: test
  script:
    - ./bin/phpcs.sh
  only:
    - merge_requests
