name: custom-upstream
recipe: wordpress
config:
  webroot: .
  php: '7.4'
services:
  node:
    type: node:14
    build:
      - npm install
    ssl: true
  appserver:
    xdebug: true
    config:
      php: .vscode/php.ini
