name: hoverboard-custom-upstream
recipe: pantheon
config:
  framework: wordpress
  site: hoverboard-custom-upstream
  id: 719d804d-d089-4177-a3f1-2d64a84e2ea5
  composer_version: '2'
services:
  node:
    type: node:14
    build:
      - npm install
    ssl: true
  appserver:
    xdebug: true
    config:
      php: .vscode/php.ini
tooling:
  npm:
    service: node
proxy:
  node:
    - bs.hoverboard-custom-upstream.lndo.site:3000
