name: hoverboard
recipe: wordpress
config:
  webroot: .
  php: "8.4"
tooling:
  pull:
    service: appserver
    description: Pulls database and files down
    cmd: wp migratedb pull https://hoverboardstudios.com vNbLWHvHPAvSLti87oWvmDxUULjuPWP+8rIdRYHG --find=//hoverboardstudios.com,/sites/hoverboardstudios.com/files --replace=//hoverboard.lndo.site,/app --skip-replace-guids --media=all
